# Generated by Django 4.2.7 on 2023-11-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_company_company_bgimg_company_company_logotip'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_location',
            field=models.CharField(default='Amir Temur 11A, Toshkent', max_length=500),
        ),
        migrations.AlterField(
            model_name='company_photo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_photo_set', to='landing_page.company'),
        ),
    ]
