# Generated by Django 4.2.7 on 2023-11-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_company_company_location_alter_company_photo_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_phone_number',
            field=models.CharField(default='1234567890', max_length=20),
        ),
    ]
