# Generated by Django 4.2.7 on 2023-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_company_company_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_instagram_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='company',
            name='company_location_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='company',
            name='company_telegram_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
