# Generated by Django 4.2.7 on 2023-11-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('information', models.TextField()),
                ('photo', models.ImageField(default='default_profile_pic.jpg', upload_to='')),
            ],
        ),
    ]
